name: CoinFlipper
version: 2.4_4
api-version: 1.15
author: gronnmann
main: io.github.gronnmann.coinflipper.Main
depend: [Vault]
softdepend: [ProtocolLib, CombatTagPlus, PvPManager, ChatPerWorld, CombatLogX, PlaceholderAPI]
commands:
    coinflipper:
        aliases: [ cf, coinflip ]